# This file only contains some config variables:

# Index prefix: The prefix of the index in elasticsearch. Ex: gastos

index="mec-servidores"

# Filter: An associative array that will be used on 'egrep' to filter data to get only relevant universities.
# The key must be the university initials and the value should be the university name (equal to its name in Portal Transparencia's csv!).

declare -A filter
filter=(
    [ufal]="UNIVERSIDADE FEDERAL DE ALAGOAS"
    [ufba]="UNIVERSIDADE FEDERAL DA BAHIA"
    [ufc]="UNIVERSIDADE FEDERAL DO CEARA"
    [ufes]="UNIVERSIDADE FEDERAL DO ESPIRITO SANTO"
    [ufg]="UNIVERSIDADE FEDERAL DE GOIAS"
    [uff]="UNIVERSIDADE FEDERAL FLUMINENSE"
    [ufjf]="UNIVERSIDADE FEDERAL DE JUIZ DE FORA"
    [ufmg]="UNIVERSIDADE FEDERAL DE MINAS GERAIS"
    [ufpa]="UNIVERSIDADE FEDERAL DO PARA"
    [ufpb]="UNIVERSIDADE FEDERAL DA PARAIBA"
    [ufpr]="UNIVERSIDADE FEDERAL DO PARANA"
    [ufpe]="UNIVERSIDADE FEDERAL DE PERNAMBUCO"
    [ufrn]="UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE"
    [ufrgs]="UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL"
    [ufrj]="UNIVERSIDADE FEDERAL DO RIO DE JANEIRO"
    [ufsc]="UNIVERSIDADE FEDERAL DE SANTA CATARINA"
    [ufsm]="UNIVERSIDADE FEDERAL DE SANTA MARIA"
    [ufrpe]="UNIVERSIDADE FEDERAL RURAL DE PERNAMBUCO"
    [ufrrj]="UNIVERSIDADE FEDERAL RURAL DO RIO DE JANEIRO"
    [ufrr]="UNIVERSIDADE FEDERAL DE RORAIMA"
    [ufcg]="UNIVERSIDADE FEDERAL DE CAMPINA GRANDE"
    [ufra]="UNIVERSIDADE FEDERAL RURAL DA AMAZONIA"
    [uftm]="UNIVERSIDADE FEDERAL DO TRIANGULO MINEIRO"
    [ufvjm]="UNIVERSIDADE FED.VALES JEQUITINHONHA E MUCURI"
    [utfpr]="UNIVERSIDADE TECNOLOGICA FEDERAL DO PARANA"
    [unifal]="UNIVERSIDADE FEDERAL DE ALFENAS"
    [unifei]="UNIVERSIDADE FEDERAL DE ITAJUBA - MG"
    [unifesp]="UNIVERSIDADE FEDERAL DE SÃO PAULO"
    [ufla]="UNIVERSIDADE FEDERAL DE LAVRAS"
    [ufersa]="UNIVERSIDADE FEDERAL RURAL DO SEMI-ARIDO"
    [unirio]="UNIVERSIDADE FEDERAL DO ESTADO RIO DE JANEIRO"
    [furg]="UNIVERSIDADE FEDERAL DO RIO GRANDE - FURG"
    [ufrb]="UNIVERSIDADE FEDERAL DO RECONCAVO DA BAHIA"
    [uffs]="UNIVERSIDADE FEDERAL DA FRONTEIRA SUL"
    [ufopa]="UNIVERSIDADE FEDERAL DO OESTE DO PARA"
    [ufob]="UNIVERSIDADE FEDERAL DO OESTE DA BAHIA - UFOB"
    [ufca]="UNIVERSIDADE FEDERAL DO CARIRI - UFCA"
    [ufsb]="UNIVERSIDADE FEDERAL DO SUL DA BAHIA - UFESBA"
)

# Host: ElasticSearch's host. Examples: "localhost"

host="localhost"
